In [1]:
pip install numpy

Collecting numpy
  Downloading numpy-2.5.2-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Downloading numpy-2.5.2-cp312-cp312-win_amd64.whl (12.5 MB)
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 670.4 kB/s eta 0:00:18
   - -------------------------------------- 0.5/12.5 MB 670.4 kB/s eta 0:00:18
   -- ------------------------------------- 0.8/12.5 MB 644.9 kB/s eta 0:00:19
   --- ------------------------------------ 1.0/12.5 MB 653.7 kB/s eta 0:00:18
   --- ------------------------------------ 1.0/12.5 MB 653.7 kB/s eta 0:00:18
   --- ------------------------------------ 1.0/12.5 MB 653.7 kB/s eta 0:00:18
   ---- ----------------------------------- 1.3/12.5 MB 639.0 kB/s eta 0:00:18
   ----- ---------------------------------- 1.6/12.5 MB 665.7 kB/s eta 0:00:17
   ----- ---------------------------------- 1.8/12.5 MB 699.0 kB/s eta 0:00:16
   ----- ---------------------------------- 1.8/12.5 MB 699.0 kB/s eta 0:00:16
   ------ --------------------------------- 2.1/12.5 MB 729.3 kB/s eta 0:00:15
   ------- -------------------------------- 2.4/12.5 MB 762.6 kB/s eta 0:00:14
   -------- ------------------------------- 2.6/12.5 MB 794.6 kB/s eta 0:00:13
   --------- ------------------------------ 2.9/12.5 MB 818.4 kB/s eta 0:00:12
   ---------- ----------------------------- 3.1/12.5 MB 831.2 kB/s eta 0:00:12
   ---------- ----------------------------- 3.4/12.5 MB 860.4 kB/s eta 0:00:11
   ----------- ---------------------------- 3.7/12.5 MB 882.9 kB/s eta 0:00:10
   ------------ --------------------------- 3.9/12.5 MB 900.0 kB/s eta 0:00:10
   ------------- -------------------------- 4.2/12.5 MB 921.7 kB/s eta 0:00:09
   -------------- ------------------------- 4.5/12.5 MB 935.2 kB/s eta 0:00:09
   --------------- ------------------------ 5.0/12.5 MB 990.1 kB/s eta 0:00:08
   ---------------- ----------------------- 5.2/12.5 MB 1.0 MB/s eta 0:00:08
   ------------------ --------------------- 5.8/12.5 MB 1.1 MB/s eta 0:00:07
   ------------------- -------------------- 6.0/12.5 MB 1.1 MB/s eta 0:00:07
   -------------------- ------------------- 6.3/12.5 MB 1.1 MB/s eta 0:00:06
   --------------------- ------------------ 6.6/12.5 MB 1.1 MB/s eta 0:00:06
   ---------------------- ----------------- 7.1/12.5 MB 1.1 MB/s eta 0:00:05
   ----------------------- ---------------- 7.3/12.5 MB 1.1 MB/s eta 0:00:05
   ------------------------- -------------- 7.9/12.5 MB 1.2 MB/s eta 0:00:04
   -------------------------- ------------- 8.4/12.5 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 8.9/12.5 MB 1.2 MB/s eta 0:00:03
   ------------------------------ --------- 9.4/12.5 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 10.0/12.5 MB 1.3 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.5 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.5 MB 1.3 MB/s eta 0:00:02
   ------------------------------------ --- 11.3/12.5 MB 1.4 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 1.4 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-2.5.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:

import numpy as np
def ml_init(shape, value=2):
    return np.full(shape,value)

In [7]:
ml_init((3,3))

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [8]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mobi lap\bns_ais2_s2_ml\env\lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mobi lap\bns_ais2_s2_ml\env\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\mobi lap\bns_ais2_s2_ml\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.9 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.8 MB 1.4 MB/s eta 0:00:07
   ------ --------------------------------- 1.6/9.8 MB 1.9 MB/s eta 0:00:05
   -------- ------------------------------- 2.1/9.8 MB 2.1 MB/s eta 0:00:04
   ----------- ---------------------------- 2.9/9.8 MB 2.2 MB/s eta 0:00:04
   ------------- -------------------------- 3.4/9.8 MB 2.3 MB/s eta 0:00:03
   --------------- ------------------------ 3.9/9.8 MB 2.4 MB/s eta 0:00:03
   ------------------- -------------------- 4.7/9.8 MB 2.5 MB/s eta 0:00:03
   --------------------- ------------------ 5.2/9.8 MB 2.6 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.8 MB 2.7 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 2.7 MB/s eta 0:00:02
   ------------------------------- -------- 7.9/9.8 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 3.1 MB/s eta 0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.5 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import pandas as pd

In [12]:
s= pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [18]:
data=[[1.22,"abc"],
      [2.22,"def"],
      [3.22,"ghi"],
      [4.22,"jkl"],]
df=pd.DataFrame(data,columns=["num","string"])
type(data)

list

In [19]:
df

    num string
0  1.22    abc
1  2.22    def
2  3.22    ghi
3  4.22    jkl

In [20]:
df.columns

Index(['num', 'string'], dtype='str')

In [ ]:
display(df)

    num string
0  1.22    abc
1  2.22    def
2  3.22    ghi
3  4.22    jkl

In [23]:
df.columns=("one","two")

In [24]:
df

    one  two
0  1.22  abc
1  2.22  def
2  3.22  ghi
3  4.22  jkl

In [26]:
df.index=("r1","r2","r3","r4")

In [27]:
df

     one  two
r1  1.22  abc
r2  2.22  def
r3  3.22  ghi
r4  4.22  jkl

In [28]:
df.dtypes

one    float64
two        str
dtype: object

In [29]:
df["one"].dtype

dtype('float64')

In [30]:
df=df.astype({"one":np.float64,"two":str})

In [31]:
df.dtypes

one    float64
two        str
dtype: object

In [34]:
df["one"].max()

np.float64(4.22)

In [38]:
def range(df):
    return df.one.max()-df.one.min()

In [39]:
range(df)

np.float64(3.0)

In [40]:
df.one.value_counts()

one
1.22    1
2.22    1
3.22    1
4.22    1
Name: count, dtype: int64

In [41]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, r1 to r4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   one     4 non-null      float64
 1   two     4 non-null      str
dtypes: float64(1), str(1)
memory usage: 268.0+ bytes

In [43]:
x=df.one.values
type(x)

numpy.ndarray

In [44]:
df.values

array([[1.22, 'abc'],
       [2.22, 'def'],
       [3.22, 'ghi'],
       [4.22, 'jkl']], dtype=object)

In [45]:
df.replace("abc","shahd")

     one    two
r1  1.22  shahd
r2  2.22    def
r3  3.22    ghi
r4  4.22    jkl